// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAifAG-Kf1kcLUw5tLbQ3wR7CdDU3M44CQ',
    appId: '1:552914815369:android:5411dbc4d49b59cb743958',
    messagingSenderId: '552914815369',
    projectId: 'irrigation-system-7bb5d',
    databaseURL: 'https://irrigation-system-7bb5d-default-rtdb.firebaseio.com',
    storageBucket: 'irrigation-system-7bb5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPGQo4TgFvw6bZipe2_RynX8mbuIMJoI4',
    appId: '1:552914815369:ios:bab7d6f7993ec2ba743958',
    messagingSenderId: '552914815369',
    projectId: 'irrigation-system-7bb5d',
    databaseURL: 'https://irrigation-system-7bb5d-default-rtdb.firebaseio.com',
    storageBucket: 'irrigation-system-7bb5d.firebasestorage.app',
    iosBundleId: 'com.example.simpleIrrigationSystem',
  );

}